### PR TITLE
Merge the work of Sprint 1

### PR DESCRIPTION
**Pull request by VarioCode**
**What to do?**
- [x] Test the current deployment
The current deployment can be found at: https://negotiation-trainer.github.io/negotiation-trainer/development/index.html

When the current deployment is testen by the reviewers and approved. This PR can be merged to main.
After that I'll tag the current version as 0.1.0

### CODE REVIEW

**Review by PatrickSlag — CHANGES_REQUESTED** [review]
Wrong scene

**Comment by VarioCode** [comment]
> Wrong scene

What would be the correct one? @PatrickSlag

**Comment by PatrickSlag** [comment]
probably need to change the guid in the build settings:

    path: Assets/Scenes/ArtScene.unity
    guid: 45fc47b1d0a7b2f42992cf2c7fa060ec

**Review by PatrickSlag — DISMISSED** [review]

**Review by PatrickSlag — APPROVED** [review]

**Review by jortdr — APPROVED** [review]
lgtm

**Pull request merged**
