### PR TITLE
NT-136 Link Inventroy

### PR DESCRIPTION
**Pull request by PatrickSlag**

### CODE REVIEW

**Comment by PatrickSlag** [comment]
inv

**Comment by VarioCode** [comment]
> inv [ inv ](https://private-user-images.githubusercontent.com/44977618/316811513-658256ce-8699-4285-8284-1b581a0d4851.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTU4MzEsIm5iZiI6MTcxMTQ1NTUzMSwicGF0aCI6Ii80NDk3NzYxOC8zMTY4MTE1MTMtNjU4MjU2Y2UtODY5OS00Mjg1LTgyODQtMWI1ODFhMGQ0ODUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZWVlYzc3NjA4ZjA1ZGQwMTc4ZGU5ZTQyMmMyZTlmMGI4YzEwOTViNjcyZjc5OTIwMzNlNzAzZTE4MzE4OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GzCijqJasRcOGE5s1Bo4Kh7LEXPrzZJIJEj-Q8pdQm0) [ ](https://private-user-images.githubusercontent.com/44977618/316811513-658256ce-8699-4285-8284-1b581a0d4851.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTU4MzEsIm5iZiI6MTcxMTQ1NTUzMSwicGF0aCI6Ii80NDk3NzYxOC8zMTY4MTE1MTMtNjU4MjU2Y2UtODY5OS00Mjg1LTgyODQtMWI1ODFhMGQ0ODUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZWVlYzc3NjA4ZjA1ZGQwMTc4ZGU5ZTQyMmMyZTlmMGI4YzEwOTViNjcyZjc5OTIwMzNlNzAzZTE4MzE4OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GzCijqJasRcOGE5s1Bo4Kh7LEXPrzZJIJEj-Q8pdQm0)

Why do we still have the Resource name on both sides? I thought we agreed to put it only on one?

**Comment by jortdr** [comment]
Agreed, the top title text should be removed and all content further up.

**Comment by PatrickSlag** [comment]
probably a task for @SilverSkullCustoms

**Review by VarioCode — DISMISSED** [review]

**Review by VarioCode — APPROVED** [review]

**Review by jortdr — APPROVED** [review]
lgtm

made TD issue for the resource sprite
https://038games.atlassian.net/browse/NT-253

**Pull request merged**
