### PR TITLE
Added Storms and clutter

### PR DESCRIPTION
**Pull request by SilverSkullCustoms**
Added:

- Storm
- Soft Clouds
- Storm Clouds
- Fix render queue water shader
- Coffeetable

### CODE REVIEW

**Review by jortdr — APPROVED** [review]
LGTM

**Review by VarioCode — APPROVED** [review]

**Review by PatrickSlag — APPROVED** [review]

**Comment by SilverSkullCustoms** [comment]
WareHouse

Warehouse (first test for images)

**Review by jortdr — APPROVED** [review]
lgtm

**Review by PatrickSlag — APPROVED** [review]
👍

**Pull request merged**
